package com.appspot.manup.signup.data;

import com.appspot.manup.signup.data.DataManager.Member;

import android.content.ContentValues;

/*
 * Auto generated by generate_test_data.py
 */

final class TestData
{

    private static final ContentValues sMember0;

    private static final ContentValues[] sMembers;

    static
    {
        sMember0 = new ContentValues();
        sMember0.put(Member.PERSON_ID, "7301496");

        sMembers = new ContentValues[] {
                sMember0
        };

    } // static

    private static ContentValues getMember(final int index)
    {
        return new ContentValues(sMembers[index]);
    } // getMember(int)

    public static ContentValues[] getMembers()
    {
        return getMembers(0, sMembers.length);
    } // getMembers()

    public static ContentValues[] getMembers(final int startIndex, final int endIndex)
    {
        final ContentValues[] copies = new ContentValues[endIndex - startIndex];
        for (int i = startIndex; i < endIndex; i++)
        {
            copies[i] = getMember(i);
        }
        return copies;
    } // getMembers(int, int)

} // class TestData
