package com.appspot.manup.signup.data;

import com.appspot.manup.signup.data.DataManager.Member;

import android.content.ContentValues;

/*
 * Auto generated by generate_test_data.py
 */

final class TestData
{

    private static final ContentValues sMember0;
    private static final ContentValues sMember1;
    private static final ContentValues sMember2;
    private static final ContentValues sMember3;
    private static final ContentValues sMember4;
    private static final ContentValues sMember5;
    private static final ContentValues sMember6;
    private static final ContentValues sMember7;
    private static final ContentValues sMember8;
    private static final ContentValues sMember9;
    private static final ContentValues sMember10;
    private static final ContentValues sMember11;
    private static final ContentValues sMember12;
    private static final ContentValues sMember13;
    private static final ContentValues sMember14;
    private static final ContentValues sMember15;
    private static final ContentValues sMember16;
    private static final ContentValues sMember17;
    private static final ContentValues sMember18;
    private static final ContentValues sMember19;
    private static final ContentValues sMember20;
    private static final ContentValues sMember21;
    private static final ContentValues sMember22;
    private static final ContentValues sMember23;
    private static final ContentValues sMember24;
    private static final ContentValues sMember25;
    private static final ContentValues sMember26;
    private static final ContentValues sMember27;
    private static final ContentValues sMember28;
    private static final ContentValues sMember29;
    private static final ContentValues sMember30;
    private static final ContentValues sMember31;
    private static final ContentValues sMember32;
    private static final ContentValues sMember33;
    private static final ContentValues sMember34;
    private static final ContentValues sMember35;
    private static final ContentValues sMember36;
    private static final ContentValues sMember37;
    private static final ContentValues sMember38;
    private static final ContentValues sMember39;
    private static final ContentValues sMember40;
    private static final ContentValues sMember41;
    private static final ContentValues sMember42;
    private static final ContentValues sMember43;
    private static final ContentValues sMember44;
    private static final ContentValues sMember45;
    private static final ContentValues sMember46;
    private static final ContentValues sMember47;
    private static final ContentValues sMember48;
    private static final ContentValues sMember49;

    private static final ContentValues[] sMembers;

    static
    {
        sMember0 = new ContentValues();
        sMember0.put(Member.PERSON_ID, "1251653");

        sMember1 = new ContentValues();
        sMember1.put(Member.PERSON_ID, "7114407");
        sMember1.put(Member.LATEST_PENDING_SIGNATURE_REQUEST, "1315520076");

        sMember2 = new ContentValues();
        sMember2.put(Member.PERSON_ID, "7432208");
        sMember2.put(Member.PERSON_ID_VALIDATED, "PERSON_ID_VALIDATED_INVALID");

        sMember3 = new ContentValues();
        sMember3.put(Member.PERSON_ID, "7705189");
        sMember3.put(Member.LATEST_PENDING_SIGNATURE_REQUEST, "1315520077");
        sMember3.put(Member.PERSON_ID_VALIDATED, "PERSON_ID_VALIDATED_INVALID");

        sMember4 = new ContentValues();
        sMember4.put(Member.PERSON_ID, "1565480");
        sMember4.put(Member.PERSON_ID_VALIDATED, "PERSON_ID_VALIDATED_VALID");

        sMember5 = new ContentValues();
        sMember5.put(Member.PERSON_ID, "7467304");
        sMember5.put(Member.PERSON_ID_VALIDATED, "PERSON_ID_VALIDATED_VALID");
        sMember5.put(Member.EXTRA_INFO_STATE, "EXTRA_INFO_STATE_RETRIEVING");

        sMember6 = new ContentValues();
        sMember6.put(Member.PERSON_ID, "1186112");
        sMember6.put(Member.PERSON_ID_VALIDATED, "PERSON_ID_VALIDATED_VALID");
        sMember6.put(Member.EXTRA_INFO_STATE, "EXTRA_INFO_STATE_RETRIEVED");
        sMember6.put(Member.GIVEN_NAME, "A");
        sMember6.put(Member.SURNAME, "B");

        sMember7 = new ContentValues();
        sMember7.put(Member.PERSON_ID, "3111341");
        sMember7.put(Member.PERSON_ID_VALIDATED, "PERSON_ID_VALIDATED_VALID");
        sMember7.put(Member.EXTRA_INFO_STATE, "EXTRA_INFO_STATE_ERROR");

        sMember8 = new ContentValues();
        sMember8.put(Member.PERSON_ID, "3182520");
        sMember8.put(Member.LATEST_PENDING_SIGNATURE_REQUEST, "1315520078");
        sMember8.put(Member.PERSON_ID_VALIDATED, "PERSON_ID_VALIDATED_VALID");

        sMember9 = new ContentValues();
        sMember9.put(Member.PERSON_ID, "8067501");
        sMember9.put(Member.LATEST_PENDING_SIGNATURE_REQUEST, "1315520079");
        sMember9.put(Member.PERSON_ID_VALIDATED, "PERSON_ID_VALIDATED_VALID");
        sMember9.put(Member.EXTRA_INFO_STATE, "EXTRA_INFO_STATE_RETRIEVING");

        sMember10 = new ContentValues();
        sMember10.put(Member.PERSON_ID, "9667626");
        sMember10.put(Member.LATEST_PENDING_SIGNATURE_REQUEST, "1315520080");
        sMember10.put(Member.PERSON_ID_VALIDATED, "PERSON_ID_VALIDATED_VALID");
        sMember10.put(Member.EXTRA_INFO_STATE, "EXTRA_INFO_STATE_RETRIEVED");
        sMember10.put(Member.GIVEN_NAME, "B");
        sMember10.put(Member.SURNAME, "C");

        sMember11 = new ContentValues();
        sMember11.put(Member.PERSON_ID, "5654930");
        sMember11.put(Member.LATEST_PENDING_SIGNATURE_REQUEST, "1315520081");
        sMember11.put(Member.PERSON_ID_VALIDATED, "PERSON_ID_VALIDATED_VALID");
        sMember11.put(Member.EXTRA_INFO_STATE, "EXTRA_INFO_STATE_ERROR");

        sMember12 = new ContentValues();
        sMember12.put(Member.PERSON_ID, "8285035");

        sMember13 = new ContentValues();
        sMember13.put(Member.PERSON_ID, "1983885");

        sMember14 = new ContentValues();
        sMember14.put(Member.PERSON_ID, "2903217");

        sMember15 = new ContentValues();
        sMember15.put(Member.PERSON_ID, "1241806");

        sMember16 = new ContentValues();
        sMember16.put(Member.PERSON_ID, "7958893");

        sMember17 = new ContentValues();
        sMember17.put(Member.PERSON_ID, "2715489");

        sMember18 = new ContentValues();
        sMember18.put(Member.PERSON_ID, "1471562");

        sMember19 = new ContentValues();
        sMember19.put(Member.PERSON_ID, "8211282");

        sMember20 = new ContentValues();
        sMember20.put(Member.PERSON_ID, "4687728");

        sMember21 = new ContentValues();
        sMember21.put(Member.PERSON_ID, "9106333");

        sMember22 = new ContentValues();
        sMember22.put(Member.PERSON_ID, "1654818");

        sMember23 = new ContentValues();
        sMember23.put(Member.PERSON_ID, "5418022");

        sMember24 = new ContentValues();
        sMember24.put(Member.PERSON_ID, "2247532");

        sMember25 = new ContentValues();
        sMember25.put(Member.PERSON_ID, "5175942");

        sMember26 = new ContentValues();
        sMember26.put(Member.PERSON_ID, "9323315");

        sMember27 = new ContentValues();
        sMember27.put(Member.PERSON_ID, "9375179");
        sMember27.put(Member.SIGNATURE_STATE, "SIGNATURE_STATE_CAPTURED");

        sMember28 = new ContentValues();
        sMember28.put(Member.PERSON_ID, "1537265");
        sMember28.put(Member.LATEST_PENDING_SIGNATURE_REQUEST, "1315520082");
        sMember28.put(Member.SIGNATURE_STATE, "SIGNATURE_STATE_CAPTURED");

        sMember29 = new ContentValues();
        sMember29.put(Member.PERSON_ID, "2506188");
        sMember29.put(Member.PERSON_ID_VALIDATED, "PERSON_ID_VALIDATED_INVALID");
        sMember29.put(Member.SIGNATURE_STATE, "SIGNATURE_STATE_CAPTURED");

        sMember30 = new ContentValues();
        sMember30.put(Member.PERSON_ID, "9155487");
        sMember30.put(Member.LATEST_PENDING_SIGNATURE_REQUEST, "1315520083");
        sMember30.put(Member.PERSON_ID_VALIDATED, "PERSON_ID_VALIDATED_INVALID");
        sMember30.put(Member.SIGNATURE_STATE, "SIGNATURE_STATE_CAPTURED");

        sMember31 = new ContentValues();
        sMember31.put(Member.PERSON_ID, "1156772");

        sMember32 = new ContentValues();
        sMember32.put(Member.PERSON_ID, "2543068");

        sMember33 = new ContentValues();
        sMember33.put(Member.PERSON_ID, "1606997");

        sMember34 = new ContentValues();
        sMember34.put(Member.PERSON_ID, "6997723");

        sMember35 = new ContentValues();
        sMember35.put(Member.PERSON_ID, "9059011");

        sMember36 = new ContentValues();
        sMember36.put(Member.PERSON_ID, "2636314");

        sMember37 = new ContentValues();
        sMember37.put(Member.PERSON_ID, "3736089");

        sMember38 = new ContentValues();
        sMember38.put(Member.PERSON_ID, "7341371");

        sMember39 = new ContentValues();
        sMember39.put(Member.PERSON_ID, "4549000");

        sMember40 = new ContentValues();
        sMember40.put(Member.PERSON_ID, "7919686");
        sMember40.put(Member.LATEST_PENDING_SIGNATURE_REQUEST, "1315321077");

        sMember41 = new ContentValues();
        sMember41.put(Member.PERSON_ID, "6252746");
        sMember41.put(Member.LATEST_PENDING_SIGNATURE_REQUEST, "1315322077");
        sMember41.put(Member.PERSON_ID_VALIDATED, "PERSON_ID_VALIDATED_VALID");
        sMember41.put(Member.EXTRA_INFO_STATE, "EXTRA_INFO_STATE_RETRIEVING");

        sMember42 = new ContentValues();

        sMember43 = new ContentValues();

        sMember44 = new ContentValues();

        sMember45 = new ContentValues();

        sMember46 = new ContentValues();

        sMember47 = new ContentValues();

        sMember48 = new ContentValues();
        sMember48.put(Member.PERSON_ID, "7388261");
        sMember48.put(Member.LATEST_PENDING_SIGNATURE_REQUEST, "1415321077");
        sMember48.put(Member.PERSON_ID_VALIDATED, "PERSON_ID_VALIDATED_VALID");
        sMember48.put(Member.EXTRA_INFO_STATE, "EXTRA_INFO_STATE_RETRIEVED");
        sMember48.put(Member.GIVEN_NAME, "Tariq");
        sMember48.put(Member.SURNAME, "Patel");
        sMember48.put(Member.SIGNATURE_STATE, "SIGNATURE_STATE_UPLOADED");

        sMember49 = new ContentValues();
        sMember49.put(Member.PERSON_ID, "7388261");

        sMembers = new ContentValues[] {
                sMember0,
                sMember1,
                sMember2,
                sMember3,
                sMember4,
                sMember5,
                sMember6,
                sMember7,
                sMember8,
                sMember9,
                sMember10,
                sMember11,
                sMember12,
                sMember13,
                sMember14,
                sMember15,
                sMember16,
                sMember17,
                sMember18,
                sMember19,
                sMember20,
                sMember21,
                sMember22,
                sMember23,
                sMember24,
                sMember25,
                sMember26,
                sMember27,
                sMember28,
                sMember29,
                sMember30,
                sMember31,
                sMember32,
                sMember33,
                sMember34,
                sMember35,
                sMember36,
                sMember37,
                sMember38,
                sMember39,
                sMember40,
                sMember41,
                sMember42,
                sMember43,
                sMember44,
                sMember45,
                sMember46,
                sMember47,
                sMember48,
                sMember49
        };

    } // static

    private static ContentValues getMember(final int index)
    {
        return new ContentValues(sMembers[index]);
    } // getMember(int)

    public static ContentValues[] getMembers()
    {
        return getMembers(0, sMembers.length);
    } // getMembers()

    public static ContentValues[] getMembers(final int startIndex, final int endIndex)
    {
        final ContentValues[] copies = new ContentValues[endIndex - startIndex];
        for (int i = startIndex; i < endIndex; i++)
        {
            copies[i] = getMember(i);
        }
        return copies;
    } // getMembers(int, int)

} // class TestData
